name: Setup GitHub CLI Actions
description:
  Install GitHub CLI on self-hosted runners with multi-platform support
author: Hercules

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: terminal
  color: gray-dark

# Define your inputs here.
inputs:
  version:
    description:
      Version of GitHub CLI to install (without v prefix). Defaults to latest
    required: false
    default: latest

# Define your outputs here.
outputs:
  version:
    description: The version of GitHub CLI that was installed

runs:
  using: node20
  main: dist/index.js
